[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)

rustflags = [
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  #"-C", "link-arg=--nmagic",

  # LLD (shipped with the Rust toolchain) is used as the default linker
  #"-C", "link-arg=-Tlink.x",

  #"-C", "link-arg=--verbose",
  #"-C", "--emit=obj"
]

[target.thumbv7em-none-eabihf]
# This can also be passed to rustc via a codegen option: "-C linker=...".
linker = "/home/rgoetz/tools/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-ld"